In [1]:
import numpy as np

# np.logical_and, or, xor, not
https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_and.html 

- logical_and : 배열 원소가 and 조건을 만족하는지 Boolean 형태 배열로 출력(만족하면 True)
- logical_not : 배열 원소가 not 조건을 만족하는지 Boolean 형태 배열로 출력(만족하지 않으면 True)

- logical_or : 배열 원소가 or 조건을 만족하는지 Boolean 형태 배열로 출력
- logical_xor : 배열 원소가 xor 조건을 만족하는지 Boolean 형태 배열로 출력


In [2]:
y_pred = np.arange(5)

**1) np.logical_and**

In [3]:
np.logical_and(y_pred>2, y_pred<5) # 답 : 3, 4

array([False, False, False,  True,  True])

**2) np.logical_not**

In [4]:
np.logical_not(y_pred>2) # 답: 1, 2

array([ True,  True,  True, False, False])

**3) np.logical_or**

In [5]:
np.logical_or(y_pred<2, y_pred>4) # 답: 1, 5

array([ True,  True, False, False, False])

**4) np.logical_xor**

In [6]:
np.logical_xor(y_pred>2, y_pred>4) # 답: 3, 4

array([False, False, False,  True,  True])

## 추가 기능

1) out: 인풋과 같은 크기의 배열을 지정해주면 T/F가 아니라 1,0으로 출력됨

In [7]:
y_pred = np.array([[1,2,3,4,5],[5,2,3,4,5]])

In [8]:
np.logical_and(y_pred>2, y_pred<5, out=np.zeros((2,5)))

array([[0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.]])

## 사용 예시

- 배열에서 조건을 만족하는 원소만 찾아서 값을 바꿔줄 수 있다. 
- 예를 들어, 분류 문제를 회귀로 예측했을 때 Threshhold별로 Label 지정이 용이하다.

In [9]:
reg_pred = np.random.randint(10, size=10) # 회귀 예측 결과
clf_pred = reg_pred.copy()
clf_pred

array([6, 4, 5, 9, 3, 3, 5, 8, 6, 0])

In [10]:
np.logical_and(reg_pred>2, reg_pred<8) # 과정1 : and 연산

array([ True,  True,  True, False,  True,  True,  True, False,  True,
       False])

In [11]:
np.where(np.logical_and(reg_pred>2, reg_pred<8)) # 과정2 : 인덱스 출력

(array([0, 1, 2, 4, 5, 6, 8], dtype=int64),)

In [12]:
# 과정 3: 과정1, 2 조합하여 계산 
clf_pred[reg_pred<=2] = 0
clf_pred[np.logical_and(reg_pred>2, reg_pred<8)] = 1
clf_pred[reg_pred>=8] = 2

In [13]:
clf_pred

array([1, 1, 1, 2, 1, 1, 1, 2, 1, 0])